# Generated by Django 3.1.2 on 2020-10-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=30, verbose_name='Admission Name')),
                ('admission_date', models.DateField(blank=True, verbose_name='Admission Date')),
                ('roll_no', models.IntegerField(default=False, verbose_name='Roll No.')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('aadhar_no', models.CharField(blank=True, max_length=30, verbose_name='Aadhar No.')),
                ('mother_name', models.CharField(blank=True, max_length=40, verbose_name="Mother's name")),
                ('mother_aadhar', models.CharField(blank=True, max_length=30, verbose_name="Mother's Aadhar No.")),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name="Father's Name")),
                ('father_aadhar', models.CharField(blank=True, max_length=30, verbose_name="Father's Aadhar No.")),
                ('dob', models.DateField(verbose_name='D.O.B')),
                ('mobile_1', models.CharField(blank=True, max_length=10)),
                ('mobile_2', models.CharField(blank=True, max_length=10)),
                ('pr_addr', models.CharField(blank=True, max_length=100, verbose_name='Present Address')),
                ('pm_addr', models.CharField(blank=True, max_length=100, verbose_name='Permanent Address')),
                ('email_id', models.EmailField(blank=True, max_length=40)),
                ('Feecategory', models.CharField(blank=True, max_length=30)),
                ('blood_grp', models.CharField(blank=True, max_length=5)),
                ('ref_admn_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference admission no. of Ex-Student')),
                ('action', models.CharField(blank=True, max_length=10, verbose_name='Action')),
                ('arrear_due', models.CharField(blank=True, max_length=10, verbose_name='Arrear Due')),
                ('ttod', models.CharField(blank=True, max_length=10, verbose_name='Total Onetime Due')),
                ('ttnd', models.CharField(blank=True, max_length=10, verbose_name='Total Normal Due')),
                ('due', models.BooleanField(blank=True, default=None, null=True, verbose_name='Due(YES/NO)')),
                ('Religion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studentsapp.religion')),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsapp.caste')),
                ('class_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.class', verbose_name='Class-Sec')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.gender')),
            ],
        ),
    ]
