# Generated by Django 3.1.2 on 2020-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_auto_20201026_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='fee_category',
            options={'verbose_name': 'Fee category', 'verbose_name_plural': 'Fee categories'},
        ),
    ]
