# Generated by Django 3.1.2 on 2020-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_auto_20201109_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=30, verbose_name='Admission Number'),
        ),
    ]
