# Generated by Django 3.1.2 on 2020-11-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0004_auto_20201109_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='student',
            name='Religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentsapp.religion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='arrear_due',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Arrear Due'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_grp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ttnd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Normal Due'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ttod',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Onetime Due'),
        ),
    ]
