# Generated by Django 3.1.2 on 2020-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0006_auto_20201109_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=40, verbose_name='Class')),
                ('subs_fee', models.IntegerField(max_length=30, verbose_name='Subsidiary Fee')),
                ('lab_fee', models.IntegerField(max_length=30, verbose_name='Laboratory Fee')),
                ('tut_fee', models.IntegerField(max_length=30, verbose_name='Tuition Fee')),
                ('comp_fee', models.IntegerField(max_length=30, verbose_name='Computer Fee')),
                ('one_time', models.IntegerField(max_length=30, verbose_name='OneTime Fee')),
                ('normal', models.IntegerField(max_length=30, verbose_name='Normal Fee')),
            ],
            options={
                'verbose_name': 'Fee structure',
                'verbose_name_plural': 'Fee structure',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tc',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='TC(YES/NO)'),
        ),
    ]
