# Generated by Django 3.1.2 on 2020-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0009_auto_20201117_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Admission Number'),
        ),
    ]
