# Generated by Django 3.1.2 on 2020-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0012_auto_20201118_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_grp',
            field=models.CharField(blank=True, choices=[('type', 'AB+'), ('type', 'AB-'), ('type', 'A+'), ('type', 'A-'), ('type', 'B+'), ('type', 'B-'), ('type', 'O+'), ('type', 'O-')], default=None, max_length=5, null=True, verbose_name='Blood Group'),
        ),
    ]
