# Generated by Django 3.1.2 on 2020-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0014_auto_20201118_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Roll No.'),
        ),
    ]
