# Generated by Django 3.1.2 on 2020-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0015_auto_20201118_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aadhar No.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_aadhar',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Father's Aadhar No."),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_aadhar',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Mother's Aadhar No."),
        ),
    ]
