# Generated by Django 3.1.2 on 2020-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0016_auto_20201118_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Feecategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pm_addr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pr_addr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Present Address'),
        ),
    ]
