# Generated by Django 3.1.2 on 2020-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0017_auto_20201118_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Feecategory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='action',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Action'),
        ),
    ]
