# Generated by Django 3.1.2 on 2020-11-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0018_auto_20201118_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Feecategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
